baseURL = 'https://td.shaojiemike.top/'
languageCode = 'en-us'
theme = "topdown"
title = 'Shaojie Tan'

[params.logo]
logo_text = "ğ“¢ğ“±ğ“ªğ“¸ ğ“³ğ“²ğ“®" # using text instead of logo from https://stylized-letters.aidbo.fun/
longlogo = "images/tsj-en.png"
longlogo_size = "40px"
favicon = "tsj-light3.png"
[params.pic]
backgroundPic = "images/first.jpg"
quotePic = "images/second.jpg"

###  info in first layer bar
[params.barinfo]
text = "External Links:"

[[params.barinfo.main]]
name = "Note"
link = "https://shaojiemike.top/"

[[params.barinfo.main]]
name = "Secret"
link = "http://wiki.shaojiemike.top:8333/"

[[params.barinfo.main]]
name = "Icarus"
link = "https://icarus.shaojiemike.top/"



[[menu.main]]
name = "Highlights"
url = "/news" # folder
weight = 5

[[menu.main]]
name = "Events"
url = "/Events" # folder
weight = 6

[[menu.main]]
name = "Review"
url = "/review" # folder
weight = 7

[[menu.main]]
name = "Life"
url = "/life" # folder
weight = 8

[[menu.main]]
name = "About"
url = "about" # file
weight = 9

# admonition
[markup.goldmark.renderer]
  unsafe = true
